### ISSUE TITLE
Harbor-Defenses

### ISSUE THREAD

**Issue by beelee1** [triplea-maps/over_the_top#10]
Hi @jdimeo not sure if you're around anymore, but I wanted to ask if it was ok to use your or GenerationKills image for a triplea mod. I was gonna tweak it some as well, color the roundel, so not an exact replica. I didn't know until recently that images are private ? i guess ? Idk, I always thought open source was good to go and give credit when you can, but ... :)

Anyway, I'm graphically challenged. :) and yours looks badass :) 

Hope all is well
P

**Comment by jdimeo** [comment]
Thanks for asking! Yes, @GenerationKILL did all the artwork and would be the one to say, but I'm guessing it's OK to use especially if it's just for more TripleA maps and not something else? Good to hear from you!

**Comment by beelee1** [comment]
Great ! Thank You. I'll ask him as we'll and give you guys a plug in the
credits and at the A&A site :)

**Comment by beelee1** [comment]
Hi @GenerationKILL as you can see from the above posts, wanted to know if it was ok to use your Harbor-Defenses image in a triplea mod ? It won't be exact, as i'm gonna color the roundel. 

I don't remember if we ever talked, but your images are Badass ! Well Done ! I'm going to use it for [global_40_expansion_uhd_boxes](https://github.com/beelee1/global_40_expansion_uhd_boxes) the Danish guys are thinking about adding Naval Mines :). 

Also, it uses mostly Frostion's units, which are pretty cool too, in case you'd like to check out his work :)

Hope all is well in your World :)
P

**Comment by GenerationKILL** [comment]
Ok by me!

**Comment by beelee1** [comment]
:) Right Arm ! Thank You
